services:
  - type: web
    name: lejintao-mnist-cnn-digit-recognizer
    runtime: python
    plan: free
    rootDir: competition3_digit_recognizer/cnn_digit_web_app
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
